services:
  - type: web
    name: backend-groseries-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
